# Generated by Django 4.0.4 on 2022-05-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pokeapi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_poke', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
